package kiwistudent;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

//TODO: Create Assignment class to encapsulate logic and seperate from interface logic.
//TODO: When assignment class created, make functionality to load whole assignment and not just one question
//TODO: timers?
//TODO: deny access to tables with student/question info
//TODO: deny use of update statements
/**
 * Creates assignment interface.
 * @author Tala Ross(rsstal002)
 * @author Nikai Jagganath (jggnik001)
 * @author Steve Shun Wang (wngshu003)
 */
public class AssignmentFrame extends javax.swing.JFrame {
    
    
    //Model instance variables:
    //TODO: move most to assigment class
    
    //TODO: update to get from server:
    /**
     * Number of questions in an assignment.
     */
    public static final int NUM_QUESTIONS= 1;
    
    /**
     * Home page frame to return to when done viewing grade.
     */
    static HomeFrame home;
    
    /**
     * Student object containing and controlling information relevant to logged
     * in student.
     */
    static Student student;
    
    //TODO: load questions into list when multiple question assignment functionality created
    /**
     * List of questions in assignment.
     */
    static ArrayList<Question> questionList;
    
    //TODO: remove when multiple question assignment functionality created
    /**
     * Single question being loaded to frame(in this deliverable stage).
     */
    Question q;
    
    
    //Constructor:
    
    /**
     * Creates new form AssignmentFrame.
     * @param home Home frame to return to when done viewing grade.
     * @param student Student object representing logged in student.
     */
    public AssignmentFrame(HomeFrame home, Student student) {
        this.home = home;
        this.student = student;
        initComponents();
        questionList = new ArrayList<>();
        q = generateQuestions();    //TODO: remove later. Generate assignment object and load first question
        txtaQuestion.setText("Question:\n"+q.getQuestion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaQuestion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaFeedback = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtfAnswer = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnShowSchema = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        txtfMark = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtaOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtaQuestion.setEditable(false);
        txtaQuestion.setColumns(20);
        txtaQuestion.setRows(5);
        txtaQuestion.setText("Question:");
        jScrollPane1.setViewportView(txtaQuestion);

        txtaFeedback.setEditable(false);
        txtaFeedback.setColumns(20);
        txtaFeedback.setRows(5);
        txtaFeedback.setText("Feedback:");
        jScrollPane2.setViewportView(txtaFeedback);

        jLabel1.setText("Enter your answer:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnShowSchema.setText("Show Schema");
        btnShowSchema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSchemaActionPerformed(evt);
            }
        });

        btnCheck.setText("Check Output");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        txtfMark.setEditable(false);

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jLabel2.setText("Mark:");

        txtaOutput.setEditable(false);
        txtaOutput.setColumns(20);
        txtaOutput.setRows(5);
        txtaOutput.setText("Output:");
        jScrollPane4.setViewportView(txtaOutput);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowSchema))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfMark, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(txtfAnswer))
                    .addComponent(jScrollPane4)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnShowSchema)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCheck))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome)
                    .addComponent(btnNext)
                    .addComponent(txtfMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Action performed methods:
    
    /**
     * Gets answer statement from text field and uses this to mark assignment.
     * @param evt Click "Submit" button.
     */
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String answer = txtfAnswer.getText();
        int mark = q.mark(answer);
        if (mark>=0) {  //no error
            txtfMark.setText(mark + "/" + q.getDifficulty()*Question.MARK_RANGE[2]);
        }
        txtaFeedback.setText(q.getFeedback(answer));
        btnSubmit.setEnabled(false);
    }//GEN-LAST:event_btnSubmitActionPerformed
    
    /**
     * Goes back to home frame.
     * @param evt Click "Home" button.
     */
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        this.setVisible(false);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed
    
    //TODO: Create next functionality and enable next button.
    /**
     * Goes to next question.
     * Mark for current question set to zero if not submitted.
     * @param evt 
     */
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        
    }//GEN-LAST:event_btnNextActionPerformed
    
    //TODO: create functionality to generate schema based on query data and not use saved image.
    /**
     * Shows pop-up frame with picture representing the query data schema.
     * @param evt Click "Show Schema" button.
     */
    private void btnShowSchemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSchemaActionPerformed
        ImageIcon icon = new ImageIcon("schema.jpg");
        JOptionPane.showMessageDialog(null, "", "Schema", JOptionPane.PLAIN_MESSAGE, icon);
    }//GEN-LAST:event_btnShowSchemaActionPerformed
    
    /**
     * Processes student's sql statement in text field and shows what the
     * output would be.
     * @param evt Click "Check Output" button.
     */
    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        String statement = txtfAnswer.getText();
        String output = Question.check(statement);
        txtaOutput.setText(output);
    }//GEN-LAST:event_btnCheckActionPerformed

    
    //Helper method for assignment generation:
    
    //TODO: create list and move functionality to assignment class
    //TODO: make fair question selection
    /**
     * Generates list of questions that make up the assignment.
     * @return The list of questions. (Currently just one question)
     */
    private static Question generateQuestions() {
        
        try {
            //Setup database connection: requires mysql "KiwiDB" named database on host with user="root" and pass="mysql"
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/KiwiDB", "root", "mysql");

            //Get the number of questions in the questions table:
            String query = "SELECT COUNT(*) AS noRows FROM Questions";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            rs.next();  //take cursor to first row
            int noRows = rs.getInt("noRows");
            
            //Setup:
            boolean [] usedQuestions = new boolean [noRows];    //true if used otherwise false (used to avoid duplicates)
            int random = 0;
            Random rnd = new Random();
            
            //Get list of questions:
            //**for (int i=0; i<noQuestions; i++) {
            
            //Get question number to query:
            boolean used = true;
            while (used) {  //loop until unused question number found
                random =  rnd.nextInt(noRows) + 1;
                if (!usedQuestions[random-1]) {
                    usedQuestions[random-1] = true;
                    used = false;
                }
            }
            
            //Get question from questions table:
            query = "SELECT * FROM Questions WHERE QuestionNo LIKE '" + random + "'";
            rs = st.executeQuery(query);
            
            //Create question object and update
            Question question = new Question();
            while (rs.next()) {
                String tempQuestion = rs.getString("Question");
                String answer = rs.getString("Answer");
                int difficulty = rs.getInt("Difficulty");
                question = new Question(tempQuestion, answer, difficulty);
                System.out.format("%s, %s, %s\n", question, answer, difficulty );   //DEBUG
            }
            
            //Clean up:
            rs.close();
            st.close();
            conn.close();
            
            return question;
            
            //**end for loop
            //return question list
            }
        catch (SQLException e) {
            System.out.println("Error: Problem query database or reading result set output.");
            System.out.println(e); 
            }
        catch (Exception e) {
            System.out.println("Error: Problem connecting to database/loading driver.");
            System.out.println(e);
            }
        
        return null;    //question not created
    }
    
    
    //Main method:
    
    /**
     * Runs assignment frame.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignmentFrame(home, student).setVisible(true);
            }
        });
    }

    
    //Interface instance variables:
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnShowSchema;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtaFeedback;
    private javax.swing.JTextArea txtaOutput;
    private javax.swing.JTextArea txtaQuestion;
    private javax.swing.JTextField txtfAnswer;
    private javax.swing.JTextField txtfMark;
    // End of variables declaration//GEN-END:variables
    
    
    
}
