package kiwi.kiwilecturer;

import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * Interface for lecturer input.
 * @author Tala Ross(rsstal002)
 * @author Nikai Jagganath (jggnik001)
 * @author Steve Shun Wang (wngshu003)
 */
//TODO: handle crash close and close DB connection on close
public class HomeFrame extends javax.swing.JFrame {
    
    
    //Model instance variables: files to upload 
    
    /**
     * Students info csv file.
     */
    private String studentPath;
    
    /**
     * Question-answer pairs csv file.
     */
    private String questionsPath;
    
    /**
     * Array of csv files representing query data.
     */
    private String [] dataFilePaths;
    private String [] dataFileNames;
    
    /**
     * Path of the schema image.
     */
    private String schemaPath;
    
    //Constructor:
    
    /**
     * Creates new form HomeFrame.
     */
    Lecturer lecturer;
    boolean connected;
    
    public HomeFrame() {
        initComponents();
        txtaMarks.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 13));
        try {
            
            lecturer = new Lecturer();
            connected = lecturer.isConnected();
        } catch (IOException | ClassNotFoundException ex) {
            connected = false;
        }
        checkConnect();
    }
    
    private void checkConnect(){
        if (connected) {
            txtfFeedback.setText("Connected to database");
            enableButtons();
            btnReconnect.setEnabled(false);
        } else {
            txtfFeedback.setText("Not connected to database");
            disableButtons();
            btnReconnect.setEnabled(true);
        }
    }
    
    private void disableButtons(){
        btnGradeDescending.setEnabled(false);
        btnQueryData.setEnabled(false);
        btnQuestions.setEnabled(false);
        btnStudentCSV.setEnabled(false);
        btnUploadQueryData.setEnabled(false);
        btnView.setEnabled(false);
    }
    
    private void enableButtons(){
        btnGradeDescending.setEnabled(true);
        btnQueryData.setEnabled(true);
        btnQuestions.setEnabled(true);
        btnStudentCSV.setEnabled(true);
        btnUploadQueryData.setEnabled(true);
        btnView.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupAssignmentType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblUpload = new javax.swing.JLabel();
        btnStudentCSV = new javax.swing.JButton();
        btnQuestions = new javax.swing.JButton();
        btnQueryData = new javax.swing.JButton();
        txtfQuestionsFilename = new javax.swing.JTextField();
        txtfQueryDataFilename = new javax.swing.JTextField();
        txtfStudentFilename = new javax.swing.JTextField();
        btnUploadQueryData = new javax.swing.JButton();
        lblViewGrades = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaMarks = new javax.swing.JTextArea();
        btnGradeDescending = new javax.swing.JButton();
        btnReconnect = new javax.swing.JButton();
        txtfFeedback = new javax.swing.JTextField();
        lblNoSubmissions = new javax.swing.JLabel();
        lblNoQuestions = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        btnInfoUpload = new javax.swing.JButton();
        btnSchemaPath = new javax.swing.JButton();
        txtfSchemaPath = new javax.swing.JTextField();
        btnUploadStudent = new javax.swing.JButton();
        btnUploadQuestions = new javax.swing.JButton();
        jdcDate = new com.toedter.calendar.JDateChooser();
        lblColon1 = new javax.swing.JLabel();
        lblColon2 = new javax.swing.JLabel();
        jSpinNoSubmission = new javax.swing.JSpinner();
        jSpinNoQuestions = new javax.swing.JSpinner();
        rbtnAssignment = new javax.swing.JRadioButton();
        rbtnClosedPrac = new javax.swing.JRadioButton();
        btnResetStudents = new javax.swing.JButton();
        btnResetQuestions = new javax.swing.JButton();
        btnResetQueryData = new javax.swing.JButton();
        lblUD = new javax.swing.JLabel();
        lblUDstudentNo = new javax.swing.JLabel();
        lblUDdate = new javax.swing.JLabel();
        lblUDtime = new javax.swing.JLabel();
        txtfUDstudentNo = new javax.swing.JTextField();
        jdcUDdate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnUpdateDeadline = new javax.swing.JButton();
        btnSchemaUpload = new javax.swing.JButton();
        jspHH = new javax.swing.JSpinner();
        jspMM = new javax.swing.JSpinner();
        jspSS = new javax.swing.JSpinner();
        jspUDhh = new javax.swing.JSpinner();
        jspUDmm = new javax.swing.JSpinner();
        jspUDss = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowCloser(evt);
            }
        });

        lblUpload.setText("Upload CSV Files:");

        btnStudentCSV.setText("Select student csv file");
        btnStudentCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentCSVActionPerformed(evt);
            }
        });

        btnQuestions.setText("Select questions csv file");
        btnQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestionsActionPerformed(evt);
            }
        });

        btnQueryData.setText("Select query data csv files");
        btnQueryData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryDataActionPerformed(evt);
            }
        });

        txtfQuestionsFilename.setEditable(false);

        txtfQueryDataFilename.setEditable(false);

        txtfStudentFilename.setEditable(false);

        btnUploadQueryData.setText("Upload");
        btnUploadQueryData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadQueryDataActionPerformed(evt);
            }
        });

        lblViewGrades.setText("View Student Grades:");

        btnView.setText("Student Number Ascending");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        txtaMarks.setEditable(false);
        txtaMarks.setColumns(20);
        txtaMarks.setRows(5);
        jScrollPane1.setViewportView(txtaMarks);

        btnGradeDescending.setText("Grade Descending");
        btnGradeDescending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradeDescendingActionPerformed(evt);
            }
        });

        btnReconnect.setText("Reconnect");
        btnReconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReconnectActionPerformed(evt);
            }
        });

        txtfFeedback.setEditable(false);

        lblNoSubmissions.setText("Enter no. submissions allowed:");

        lblNoQuestions.setText("Enter no. quiz questions:");

        lblDate.setText("Enter deadline date:");

        lblTime.setText("Enter deadline time:");

        btnInfoUpload.setText("Upload Assignment Info");
        btnInfoUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoUploadActionPerformed(evt);
            }
        });

        btnSchemaPath.setText("Select schema image");
        btnSchemaPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSchemaPathActionPerformed(evt);
            }
        });

        txtfSchemaPath.setEditable(false);

        btnUploadStudent.setText("Upload");
        btnUploadStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadStudentActionPerformed(evt);
            }
        });

        btnUploadQuestions.setText("Upload");
        btnUploadQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadQuestionsActionPerformed(evt);
            }
        });

        jdcDate.setDateFormatString("yyyy-MM-dd");

        lblColon1.setText(":");

        lblColon2.setText(":");

        jSpinNoSubmission.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jSpinNoQuestions.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnGroupAssignmentType.add(rbtnAssignment);
        rbtnAssignment.setSelected(true);
        rbtnAssignment.setText("Assignment");

        btnGroupAssignmentType.add(rbtnClosedPrac);
        rbtnClosedPrac.setText("Closed Prac Test");

        btnResetStudents.setText("Reset");
        btnResetStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetStudentsActionPerformed(evt);
            }
        });

        btnResetQuestions.setText("Reset");
        btnResetQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetQuestionsActionPerformed(evt);
            }
        });

        btnResetQueryData.setText("Reset");
        btnResetQueryData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetQueryDataActionPerformed(evt);
            }
        });

        lblUD.setText("Update Student Deadline:");

        lblUDstudentNo.setText("Student Number:");

        lblUDdate.setText("New Deadline Date:");

        lblUDtime.setText("New Deadline Time:");

        jdcUDdate.setDateFormatString("yyyy-MM-dd");

        jLabel1.setText(":");

        jLabel2.setText(":");

        btnUpdateDeadline.setText("Update");
        btnUpdateDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDeadlineActionPerformed(evt);
            }
        });

        btnSchemaUpload.setText("Upload Schema");
        btnSchemaUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSchemaUploadActionPerformed(evt);
            }
        });

        jspHH.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jspMM.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jspSS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jspUDhh.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jspUDmm.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jspUDss.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUpload)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnStudentCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtfStudentFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnQueryData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQuestions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtfQueryDataFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfQuestionsFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblViewGrades)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGradeDescending)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnView))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnSchemaPath)
                                                .addGap(55, 55, 55)
                                                .addComponent(txtfSchemaPath))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblDate)
                                                        .addComponent(lblTime)
                                                        .addComponent(lblNoQuestions)
                                                        .addComponent(lblNoSubmissions))
                                                    .addGap(55, 55, 55)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jSpinNoSubmission, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                                            .addComponent(jSpinNoQuestions))
                                                        .addComponent(jdcDate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jspHH, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(lblColon2)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jspMM, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(lblColon1)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jspSS, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addComponent(txtfFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(124, 124, 124)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblUDdate)
                                            .addGap(18, 18, 18)
                                            .addComponent(jdcUDdate, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblUDstudentNo)
                                            .addGap(29, 29, 29)
                                            .addComponent(txtfUDstudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblUD)
                                        .addComponent(rbtnClosedPrac)
                                        .addComponent(rbtnAssignment))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblUDtime)
                                        .addGap(18, 18, 18)
                                        .addComponent(jspUDhh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jspUDmm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jspUDss, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(110, 110, 110)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInfoUpload)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUploadQuestions)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnResetQuestions))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUploadStudent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnResetStudents))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUploadQueryData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnResetQueryData))
                            .addComponent(btnSchemaUpload)
                            .addComponent(btnUpdateDeadline)
                            .addComponent(btnReconnect))
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReconnect))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoSubmissions)
                    .addComponent(jSpinNoSubmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoQuestions)
                    .addComponent(jSpinNoQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(jspHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColon2)
                    .addComponent(jspMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColon1)
                    .addComponent(jspSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnAssignment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnClosedPrac)
                    .addComponent(btnInfoUpload))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSchemaPath)
                            .addComponent(txtfSchemaPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSchemaUpload))
                        .addGap(29, 29, 29)
                        .addComponent(lblUpload)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStudentCSV)
                            .addComponent(txtfStudentFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnQuestions)
                            .addComponent(txtfQuestionsFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnQueryData)
                            .addComponent(txtfQueryDataFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUploadStudent)
                            .addComponent(btnResetStudents))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUploadQuestions)
                            .addComponent(btnResetQuestions))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUploadQueryData)
                            .addComponent(btnResetQueryData))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewGrades)
                    .addComponent(btnView)
                    .addComponent(btnGradeDescending))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUD)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUDstudentNo)
                            .addComponent(txtfUDstudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUDdate))
                    .addComponent(jdcUDdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUDtime)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jspUDhh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspUDmm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspUDss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateDeadline)
                        .addGap(44, 44, 44))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    //Action performed methods:
    /**
     * Gets student csv file selected from file chooser and checks that it is
     * in fact a csv file.
     * @param evt Click "Select student csv file"
     */
    private void btnStudentCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentCSVActionPerformed
        
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fc.showOpenDialog(this);
        if (result==JFileChooser.APPROVE_OPTION) {
            //check that file is a csv
            File temp= fc.getSelectedFile();
            if (!(temp.getName().substring(temp.getName().lastIndexOf("."))).equals(".csv")) {
                JOptionPane.showMessageDialog(this, "Incorrect file upload.\nPlease upload a .csv file.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else {
                studentPath = temp.getAbsolutePath();
                txtfStudentFilename.setText(studentPath);
            }
        }
    }//GEN-LAST:event_btnStudentCSVActionPerformed
    
    /**
     * Gets questions csv file selected from file chooser and checks that it is
     * in fact a csv file.
     * @param evt Click "Select questions csv file"
     */
    private void btnQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestionsActionPerformed
        
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fc.showOpenDialog(this);
        if (result==JFileChooser.APPROVE_OPTION) {
            File temp= fc.getSelectedFile();
            if (!(temp.getName().substring(temp.getName().lastIndexOf("."))).equals(".csv")) {
                JOptionPane.showMessageDialog(this, "Incorrect file upload.\nPlease upload a .csv file.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else {
                questionsPath = temp.getAbsolutePath();
                txtfQuestionsFilename.setText(questionsPath);
            }
        }
    }//GEN-LAST:event_btnQuestionsActionPerformed
    
    /**
     * Gets query data csv files selected from file chooser and checks that
     * they are in fact a csv file.
     * @param evt Click "Select student csv files"
     */
    private void btnQueryDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryDataActionPerformed
        
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(System.getProperty("user.home")));
        fc.setMultiSelectionEnabled(true);
        int result = fc.showOpenDialog(this);
        if (result==JFileChooser.APPROVE_OPTION) {
            File [] temp= fc.getSelectedFiles();
            String [] names = new String [temp.length];
            String [] paths = new String [temp.length];
            String selected="";
            boolean flag=true;
            for (int i=0; i<temp.length; i++) {
                if (!(temp[i].getName().substring(temp[i].getName().lastIndexOf("."))).equals(".csv")) {
                    JOptionPane.showMessageDialog(this, "Incorrect file upload for one or more files.\nPlease upload .csv files.", "Error", JOptionPane.ERROR_MESSAGE);
                    flag=false;
                    break;
                }
                names[i] = temp[i].getName().substring(0, temp[i].getName().lastIndexOf("."));
                paths[i] = temp[i].getAbsolutePath();
                selected+= temp[i].getAbsolutePath()+", ";
            }
            if(flag){
                dataFilePaths = paths;
                dataFileNames = names;
                txtfQueryDataFilename.setText(selected.substring(0, selected.length()-2));
            }
        }
    }//GEN-LAST:event_btnQueryDataActionPerformed
    
    //TODO: check for failed upload and remove all "falsely" created tables and rows
    /**
     * Uploads the selected csv files.
     * @param evt Click "Upload"
     */
    private void btnUploadQueryDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadQueryDataActionPerformed
        
        String response;
        
        if (dataFilePaths!=null) {
            response = lecturer.uploadQueryData(dataFilePaths, dataFileNames);
            if (response.equals(Lecturer.SUCCESS)) {
                JOptionPane.showMessageDialog(this, "Uploaded .csv files succesfully.", "Upload successful", JOptionPane.PLAIN_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "The following files were not uploaded.\nFiles: "+response, "Upload unsuccessful", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        //clean up:
        dataFilePaths = null;
        txtfQueryDataFilename.setText("");
        
    }//GEN-LAST:event_btnUploadQueryDataActionPerformed
    
    /**
     * Gets table of student grades in ascending student number order from the
     * database.
     * @param evt Click "Student Number Ascending"
     */
    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        
        String response = lecturer.viewGradeAscStudent();
        if (response.equals(Lecturer.FAIL_CONNECT)) {
            txtaMarks.setText("Error reading grades from Students table");
        } else {
            txtaMarks.setText(response);
        }
        
    }//GEN-LAST:event_btnViewActionPerformed
    
    /**
     * Gets table of student grades in descending grade order from the
     * database.
     * @param evt Click "Grade Descending"
     */
    private void btnGradeDescendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradeDescendingActionPerformed
        
        String response = lecturer.viewGradeDescGrade();
        if (response.equals(Lecturer.FAIL_CONNECT)) {
            txtaMarks.setText("Error reading grades from Students table");
        } else {
            txtaMarks.setText(response);
        }
        
    }//GEN-LAST:event_btnGradeDescendingActionPerformed

    private void btnReconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReconnectActionPerformed
        
        try {
            System.out.println("Trying to reconnect...");
            if (lecturer == null) { //An instance of Lecturer was not created on creation of the HomeFrame
                try {
                    lecturer = new Lecturer(); //Try make a new instance of lecturer and connect to DB
                    lecturer.connectToDB();
                    connected = lecturer.isConnected();
                } catch (IOException | ClassNotFoundException e) {
                    System.out.println("Error creating a new lecturer");
                }
            } else {
                lecturer.connectToDB();
                connected = lecturer.isConnected();
            }
        } catch (IOException | ClassNotFoundException ex) {
            connected = false;
        }
        
        if (!connected) {
            JOptionPane.showMessageDialog(this, "Connection to database failed.", "Connection Error", JOptionPane.ERROR_MESSAGE);
        }        
        checkConnect();
        
    }//GEN-LAST:event_btnReconnectActionPerformed

    private void btnInfoUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoUploadActionPerformed
        
        //Send assignment information to save on server
        
        String response;
        
        try {
            jSpinNoSubmission.commitEdit();
            jSpinNoQuestions.commitEdit();
            jspHH.commitEdit();
            jspMM.commitEdit();
            jspSS.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(HomeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String noSubmissions = ""+(Integer) jSpinNoSubmission.getValue();
        String noQuestions = ""+ (Integer) jSpinNoQuestions.getValue();
        String date = ((JTextField)jdcDate.getDateEditor().getUiComponent()).getText();
        String hour = ""+(Integer) jspHH.getValue();
        String minute = ""+(Integer) jspMM.getValue();
        String second = ""+(Integer) jspSS.getValue();
        
        String time = "";
        if (Integer.parseInt(hour)<10){
            time = "0" + hour + ":";
        }else{
            time = hour +":";
        }
        if (Integer.parseInt(minute)<10){
            time = time + "0" + minute + ":";
        }else{
            time = time + minute + ":";
        }
        if (Integer.parseInt(second)<10){
            time = time + "0" + second;
        }else{
            time = time + second;
        }
        
        
        boolean closedPrac = false;
        
        //get whether the prac is closed or open
        if (rbtnClosedPrac.isSelected()) {
            closedPrac = true;
        } 
        else if(rbtnAssignment.isSelected()){
            closedPrac = false;
        }
        
        if(noSubmissions.equals("") || noQuestions.equals("") || date.equals("") || time.equals("")){
            JOptionPane.showMessageDialog(this, "Please fill in blank fields", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            
            response = lecturer.uploadAssignmentInfo(noSubmissions, noQuestions, date, time, closedPrac);
            if (response.equals(Lecturer.SUCCESS)) {
                JOptionPane.showMessageDialog(this, "Uploaded assignment information succesfully.", "Upload successful", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Assignment information not uploaded.", "Upload unsuccessful", JOptionPane.ERROR_MESSAGE);
            }
            //clean up:
            jSpinNoQuestions.setValue(1);
            jSpinNoSubmission.setValue(1);
            jdcDate.setDate(null);
            jspHH.setValue(0);
            jspMM.setValue(0);
            jspSS.setValue(0);
        }
        
    }//GEN-LAST:event_btnInfoUploadActionPerformed

    private void btnSchemaPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchemaPathActionPerformed
        
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fc.showOpenDialog(this);
        if (result==JFileChooser.APPROVE_OPTION) {
            File image = fc.getSelectedFile();
            if (image==null || !(image.getName().substring(image.getName().lastIndexOf("."))).equalsIgnoreCase(".jpg")) {
                JOptionPane.showMessageDialog(this, "Incorrect file upload.\nPlease upload a .png image.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else {
                schemaPath = image.getAbsolutePath();
                txtfSchemaPath.setText(schemaPath);
            }
        }
        
    }//GEN-LAST:event_btnSchemaPathActionPerformed

    private void btnUploadStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadStudentActionPerformed
        
        String response;
        
        if (studentPath!=null) {
            response = lecturer.uploadStudents(studentPath);
            switch (response) {
                case Lecturer.SUCCESS:
                    JOptionPane.showMessageDialog(this, 
                            "Uploaded students csv file succesfully.", 
                            "Upload Successful",JOptionPane.PLAIN_MESSAGE);
                    break;
                case Lecturer.FAIL_INPUT:
                    JOptionPane.showMessageDialog(this, 
                            "Students file was not uploaded.\n"
                            + "Provided csv file format is incorrect.\n\n"
                            + "Expected Format:\n"
                            + "StudentNo\\r\\n\n"
                            + "<student_number_1>\\r\\n\n"
                            + "<student_number_2>\\r\\n\n"
                            + "...", 
                            "Upload Unsuccessful", JOptionPane.ERROR_MESSAGE);
                    break;
                case Lecturer.FAIL_NULL:
                    JOptionPane.showMessageDialog(this, 
                            "Students file was not uploaded.\n"
                            + "Assignment information needs to be entered before\n"
                            + "the students csv file can be saved.", 
                            "Upload Unsuccessful", JOptionPane.ERROR_MESSAGE);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, 
                            "Students file was not uploaded.\n"
                            + "Problem connecting to database.", 
                            "Upload Unsuccessful", JOptionPane.ERROR_MESSAGE);
                    break;
            }
        }
        
        //clean up:
        studentPath = null;
        txtfStudentFilename.setText("");
        
    }//GEN-LAST:event_btnUploadStudentActionPerformed

    private void btnUploadQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadQuestionsActionPerformed
        
        String response;
        
        if (questionsPath!=null) {
            response = lecturer.uploadQuestions(questionsPath);
            switch (response) {
                case Lecturer.SUCCESS:
                    JOptionPane.showMessageDialog(this, 
                            "Uploaded questions csv file succesfully.", 
                            "Upload Successful",JOptionPane.PLAIN_MESSAGE);
                    break;
                case Lecturer.FAIL_INPUT:
                    JOptionPane.showMessageDialog(this, 
                            "Questions file was not uploaded.\n"
                            + "Provided csv file format is incorrect.\n\n"
                            + "Expected Format:\n"
                            + "Question,Answer,Difficulty,Type\\r\\n\n"
                            + "\"<question1>\",\"<answer1>\",<difficulty1>,<type1>\\r\\n\n"
                            + "\"<question2>\",\"<answer2>\",<difficulty2>,<type2>\\r\\n\n"
                            + "...," 
                            + "where Type in {select, arithmetic, update}.",
                            "Upload Unsuccessful", JOptionPane.ERROR_MESSAGE);
                    break;
                case Lecturer.FAIL_QUESTIONS:
                    JOptionPane.showMessageDialog(this, "Questions file was not uploaded. Please ensure the following:\n"
                            + "1. There are sufficient type-difficulty pairs.\n"
                            + "2. The assignment information has been uploaded.");
                    break;
                default:
                    JOptionPane.showMessageDialog(this, 
                            "Questions file was not uploaded."
                            + "Problem connecting to database.", 
                            "Upload Unsuccessful", JOptionPane.ERROR_MESSAGE);
                    break;
            }
        }
        
        //clean up:
        questionsPath = null;
        txtfQuestionsFilename.setText("");
        
    }//GEN-LAST:event_btnUploadQuestionsActionPerformed

    private void windowCloser(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowCloser
        if (lecturer!=null) {
            try {
                lecturer.closeConnection();
            } 
            catch (IOException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Error closing sockets.", "Socket Error", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }
        System.exit(0);
    }//GEN-LAST:event_windowCloser

    private void btnUpdateDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDeadlineActionPerformed
        
        String response = "";
        
        try {
            jspHH.commitEdit();
            jspMM.commitEdit();
            jspSS.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(HomeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        String studentNo = txtfUDstudentNo.getText();
        String date = ((JTextField)jdcUDdate.getDateEditor().getUiComponent()).getText();
        String hour = ""+(Integer) jspUDhh.getValue();
        String minute = ""+(Integer) jspUDmm.getValue();
        String second = ""+(Integer) jspUDss.getValue();
        String time = "";
        if (Integer.parseInt(hour)<10){
            time = "0" + hour + ":";
        }else{
            time = hour +":";
        }
        if (Integer.parseInt(minute)<10){
            time = time + "0" + minute + ":";
        }else{
            time = time + minute + ":";
        }
        if (Integer.parseInt(second)<10){
            time = time + "0" + second;
        }else{
            time = time + second;
        }
        
        if (!studentNo.equals("")&&studentNo.length()==6&&!date.equals(null))
        {
            response = lecturer.updateStudentDeadline(studentNo,date,time);
            if (response.equals(Lecturer.SUCCESS)) {
                JOptionPane.showMessageDialog(this, "Assignment deadline for "+studentNo+" has been updated.", "Update successful", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Deadline update for "+studentNo+" was unsuccessful.", "Unsuccessful update", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid Studnet number or date!","Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    
        //clean up:
        txtfUDstudentNo.setText("");
        jdcUDdate.setDate(null);
        jspUDhh.setValue(0);
        jspUDmm.setValue(0);
        jspUDss.setValue(0);
        
    }//GEN-LAST:event_btnUpdateDeadlineActionPerformed

    private void btnSchemaUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchemaUploadActionPerformed
        
        //Save schema image onto server
        System.out.println("Schema path: "+schemaPath);
        
        String response;

        if(schemaPath==null){
            JOptionPane.showMessageDialog(this, "Please select a schema image to upload", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            response = lecturer.uploadSchema(schemaPath);
            if (response.equals(Lecturer.SUCCESS)) {
                JOptionPane.showMessageDialog(this, "Uploaded schema succesfully.", "Upload successful", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Schema not uploaded.", "Upload unsuccessful", JOptionPane.ERROR_MESSAGE);
            }
            //clean up:
            txtfSchemaPath.setText("");            
        }
        
        
    }//GEN-LAST:event_btnSchemaUploadActionPerformed

    private void btnResetStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetStudentsActionPerformed
        
        //reset the students table
        
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the Students table?", "Warning", JOptionPane.WARNING_MESSAGE);
        
        if (option == JOptionPane.YES_OPTION) {
            String response = lecturer.resetStudents();
            if (response.equals(Lecturer.SUCCESS)) {
                JOptionPane.showMessageDialog(this, "Succesfully cleared Students table.", "Reset successful", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Students table was not cleared.", "Reset unsuccessful", JOptionPane.ERROR_MESSAGE);
            }             
        }
        
    }//GEN-LAST:event_btnResetStudentsActionPerformed

    private void btnResetQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetQuestionsActionPerformed
        
        //reset the questions table
        
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the Questions table?", "Warning", JOptionPane.WARNING_MESSAGE);
        
        if (option == JOptionPane.YES_OPTION) {
        String response = lecturer.resetQuestions();
            if (response.equals(Lecturer.SUCCESS)) {
                JOptionPane.showMessageDialog(this, "Succesfully cleared Questions table.", "Reset successful", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Questions table was not cleared.", "Reset unsuccessful", JOptionPane.ERROR_MESSAGE);
            }
        }  
        
    }//GEN-LAST:event_btnResetQuestionsActionPerformed

    private void btnResetQueryDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetQueryDataActionPerformed
       
        //reset the query data tables
        
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete all Query Data tables?", "Warning", JOptionPane.WARNING_MESSAGE);
        
        if (option == JOptionPane.YES_OPTION) {
            String response = lecturer.resetQueryData();
            if (response.equals(Lecturer.SUCCESS)) {
                JOptionPane.showMessageDialog(this, "Succesfully cleared Query Data tables.", "Reset successful", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Query Data tables were not cleared.", "Reset unsuccessful", JOptionPane.ERROR_MESSAGE);
            }
        }   
    }//GEN-LAST:event_btnResetQueryDataActionPerformed
    
    
    //Main method:
    
    /**
     * Runs the interface.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    
    //Interface instance variables:
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGradeDescending;
    private javax.swing.ButtonGroup btnGroupAssignmentType;
    private javax.swing.JButton btnInfoUpload;
    private javax.swing.JButton btnQueryData;
    private javax.swing.JButton btnQuestions;
    private javax.swing.JButton btnReconnect;
    private javax.swing.JButton btnResetQueryData;
    private javax.swing.JButton btnResetQuestions;
    private javax.swing.JButton btnResetStudents;
    private javax.swing.JButton btnSchemaPath;
    private javax.swing.JButton btnSchemaUpload;
    private javax.swing.JButton btnStudentCSV;
    private javax.swing.JButton btnUpdateDeadline;
    private javax.swing.JButton btnUploadQueryData;
    private javax.swing.JButton btnUploadQuestions;
    private javax.swing.JButton btnUploadStudent;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinNoQuestions;
    private javax.swing.JSpinner jSpinNoSubmission;
    private com.toedter.calendar.JDateChooser jdcDate;
    private com.toedter.calendar.JDateChooser jdcUDdate;
    private javax.swing.JSpinner jspHH;
    private javax.swing.JSpinner jspMM;
    private javax.swing.JSpinner jspSS;
    private javax.swing.JSpinner jspUDhh;
    private javax.swing.JSpinner jspUDmm;
    private javax.swing.JSpinner jspUDss;
    private javax.swing.JLabel lblColon1;
    private javax.swing.JLabel lblColon2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblNoQuestions;
    private javax.swing.JLabel lblNoSubmissions;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUD;
    private javax.swing.JLabel lblUDdate;
    private javax.swing.JLabel lblUDstudentNo;
    private javax.swing.JLabel lblUDtime;
    private javax.swing.JLabel lblUpload;
    private javax.swing.JLabel lblViewGrades;
    private javax.swing.JRadioButton rbtnAssignment;
    private javax.swing.JRadioButton rbtnClosedPrac;
    private javax.swing.JTextArea txtaMarks;
    private javax.swing.JTextField txtfFeedback;
    private javax.swing.JTextField txtfQueryDataFilename;
    private javax.swing.JTextField txtfQuestionsFilename;
    private javax.swing.JTextField txtfSchemaPath;
    private javax.swing.JTextField txtfStudentFilename;
    private javax.swing.JTextField txtfUDstudentNo;
    // End of variables declaration//GEN-END:variables

}
